---
title: "First Knit"
author: "Juan Padilla"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
 I went to Peteknight Highschool and I graduated in 2012. I always found Math to be a little easier. I always did do better in Math. 

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  I have a Samsung Windows computer. I would rate myself at a 6 on my computer knowledge. I have a good internet connection.
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
   I've only ever gone by name. I've never gone by a nickname.
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  I am trying to become Management in my area of work. I am pursuing a business and economics as my interested college courses. I am trying to get my Bachelors in Business Administration.
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  Yes I have visited foreign countries. I actually just returned from Germany. I have never been in the military. If I did get drafted and had to choose a branch I would choose the Air Force or the Army as I already work with aircraft that those branches own.
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  No this is my first time taking Math 115 and yes I did know that. I need to receive an A in this class. It satisfies a general requirement and a transferable course for the school I am trying to get into.
   
 






  




